revoke execute on function public.all_gates_passed(uuid) from public;
revoke execute on function public.compute_pbv(uuid) from public;
revoke execute on function public.count_qualified_commitments(uuid) from public;
revoke execute on function public.create_organization(text) from public;
revoke execute on function public.enforce_pbv_weight_total() from public;
revoke execute on function public.gate_state_json(uuid) from public;
revoke execute on function public.get_org_role(uuid) from public;
revoke execute on function public.invite_organization_member(uuid, uuid, public.org_role) from public;
revoke execute on function public.is_org_admin_for_opportunity(uuid) from public;
revoke execute on function public.is_org_member(uuid) from public;
revoke execute on function public.org_id_for_opportunity(uuid) from public;
revoke execute on function public.record_pbv_evidence(uuid, text, numeric, text) from public;
revoke execute on function public.reject_ledger_mutation() from public;
revoke execute on function public.set_updated_at() from public;
revoke execute on function public.set_validation_gate(uuid, public.gate_name, public.gate_status, text) from public;
revoke execute on function public.sync_commitment_gate(uuid) from public;
revoke execute on function public.transition_opportunity(uuid, public.opportunity_stage) from public;
revoke execute on function public.trg_sync_commitment_gate() from public;
revoke execute on function public.verify_commitment(uuid, public.verification_status) from public;

grant execute on function public.all_gates_passed(uuid) to authenticated;
grant execute on function public.compute_pbv(uuid) to authenticated;
grant execute on function public.count_qualified_commitments(uuid) to authenticated;
grant execute on function public.create_organization(text) to authenticated;
grant execute on function public.gate_state_json(uuid) to authenticated;
grant execute on function public.get_org_role(uuid) to authenticated;
grant execute on function public.invite_organization_member(uuid, uuid, public.org_role) to authenticated;
grant execute on function public.is_org_admin_for_opportunity(uuid) to authenticated;
grant execute on function public.is_org_member(uuid) to authenticated;
grant execute on function public.org_id_for_opportunity(uuid) to authenticated;
grant execute on function public.record_pbv_evidence(uuid, text, numeric, text) to authenticated;
grant execute on function public.set_validation_gate(uuid, public.gate_name, public.gate_status, text) to authenticated;
grant execute on function public.transition_opportunity(uuid, public.opportunity_stage) to authenticated;
grant execute on function public.verify_commitment(uuid, public.verification_status) to authenticated;
