-- Restores EXECUTE that revenue_insert / exit_scores_upsert / exit_scores_update RLS
-- policies depend on. 0014_rls_new_tables (originally applied as "0013_rls_new_tables")
-- added policies calling is_org_admin_for_opportunity(), but 0012 had already revoked
-- authenticated's EXECUTE on that function one migration earlier — correct at the time,
-- since nothing referenced it yet. Net effect until this migration: any OWNER/ADMIN
-- inserting a revenue snapshot or updating exit scores got a hard
-- "permission denied for function is_org_admin_for_opportunity" instead of the intended
-- RLS behavior. Confirmed live before and after this fix (see supabase/migrations/README.md).
--
-- This does not reopen the original over-exposure: the function only returns a boolean
-- derived from the caller's own role (get_org_role already scopes to auth.uid()), so it's
-- the same class of "must stay grantee because RLS calls it" function as
-- is_org_member/get_org_role/org_id_for_opportunity.
grant execute on function public.is_org_admin_for_opportunity(uuid) to authenticated;
